// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClIF-JeUfjpcTipM6sTyBlgTCe0QtoPzI',
    appId: '1:840513308213:web:16c7d21ef50fd1c2e8537c',
    messagingSenderId: '840513308213',
    projectId: 'disaster-management-app-8b0cd',
    authDomain: 'disaster-management-app-8b0cd.firebaseapp.com',
    storageBucket: 'disaster-management-app-8b0cd.firebasestorage.app',
    measurementId: 'G-ETL60891DV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcUeQCdLONUIcfeMzXWKVevxUF8z3Kw3k',
    appId: '1:840513308213:android:070dab68b4cfa771e8537c',
    messagingSenderId: '840513308213',
    projectId: 'disaster-management-app-8b0cd',
    storageBucket: 'disaster-management-app-8b0cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3u7JZtS9RMz5j5jLHjRsmgBs2ZPL3yGM',
    appId: '1:840513308213:ios:e2edde714fa534cae8537c',
    messagingSenderId: '840513308213',
    projectId: 'disaster-management-app-8b0cd',
    storageBucket: 'disaster-management-app-8b0cd.firebasestorage.app',
    iosBundleId: 'com.example.disasterManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3u7JZtS9RMz5j5jLHjRsmgBs2ZPL3yGM',
    appId: '1:840513308213:ios:e2edde714fa534cae8537c',
    messagingSenderId: '840513308213',
    projectId: 'disaster-management-app-8b0cd',
    storageBucket: 'disaster-management-app-8b0cd.firebasestorage.app',
    iosBundleId: 'com.example.disasterManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClIF-JeUfjpcTipM6sTyBlgTCe0QtoPzI',
    appId: '1:840513308213:web:366ff073034d76dbe8537c',
    messagingSenderId: '840513308213',
    projectId: 'disaster-management-app-8b0cd',
    authDomain: 'disaster-management-app-8b0cd.firebaseapp.com',
    storageBucket: 'disaster-management-app-8b0cd.firebasestorage.app',
    measurementId: 'G-BQFL9Y1KCF',
  );

}